# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_id_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_face_id_window(object):
    def setupUi(self, face_id_window):
        face_id_window.setObjectName("face_id_window")
        face_id_window.resize(350, 330)
        face_id_window.setStyleSheet("::Sign_in_window\n"
"{\n"
"border-image:url(:/sign_in/OIP-C.jpg)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(face_id_window)
        self.centralwidget.setObjectName("centralwidget")
        self.sign_in_button = QtWidgets.QPushButton(self.centralwidget)
        self.sign_in_button.setGeometry(QtCore.QRect(115, 290, 120, 30))
        self.sign_in_button.setObjectName("sign_in_button")
        self.background_image = QtWidgets.QLabel(self.centralwidget)
        self.background_image.setGeometry(QtCore.QRect(0, 0, 351, 331))
        self.background_image.setText("")
        self.background_image.setObjectName("background_image")
        self.camera_label = QtWidgets.QLabel(self.centralwidget)
        self.camera_label.setGeometry(QtCore.QRect(15, 40, 320, 240))
        self.camera_label.setText("")
        self.camera_label.setObjectName("camera_label")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setGeometry(QtCore.QRect(75, 10, 200, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.info_label.setFont(font)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.background_image.raise_()
        self.sign_in_button.raise_()
        self.camera_label.raise_()
        self.info_label.raise_()
        face_id_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(face_id_window)
        QtCore.QMetaObject.connectSlotsByName(face_id_window)

    def retranslateUi(self, face_id_window):
        _translate = QtCore.QCoreApplication.translate
        face_id_window.setWindowTitle(_translate("face_id_window", "人脸识别"))
        self.sign_in_button.setText(_translate("face_id_window", "登录"))
        self.info_label.setText(_translate("face_id_window", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">人脸识别不通过！</span></p></body></html>"))
