# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_in_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sign_in_window(object):
    def setupUi(self, Sign_in_window):
        Sign_in_window.setObjectName("Sign_in_window")
        Sign_in_window.resize(300, 300)
        Sign_in_window.setStyleSheet("::Sign_in_window\n"
"{\n"
"border-image:url(:/sign_in/OIP-C.jpg)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Sign_in_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 10, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.account_Inputer = QtWidgets.QLineEdit(self.centralwidget)
        self.account_Inputer.setGeometry(QtCore.QRect(70, 80, 200, 20))
        self.account_Inputer.setObjectName("account_Inputer")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Password_Inputer = QtWidgets.QLineEdit(self.centralwidget)
        self.Password_Inputer.setGeometry(QtCore.QRect(70, 120, 200, 20))
        self.Password_Inputer.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_Inputer.setObjectName("Password_Inputer")
        self.Teacher_QRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.Teacher_QRadio.setGeometry(QtCore.QRect(70, 170, 89, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Teacher_QRadio.setFont(font)
        self.Teacher_QRadio.setObjectName("Teacher_QRadio")
        self.Student_QRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.Student_QRadio.setGeometry(QtCore.QRect(180, 170, 89, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Student_QRadio.setFont(font)
        self.Student_QRadio.setObjectName("Student_QRadio")
        self.sign_in_button = QtWidgets.QPushButton(self.centralwidget)
        self.sign_in_button.setGeometry(QtCore.QRect(90, 210, 120, 30))
        self.sign_in_button.setObjectName("sign_in_button")
        self.sign_up_button = QtWidgets.QPushButton(self.centralwidget)
        self.sign_up_button.setGeometry(QtCore.QRect(110, 250, 80, 25))
        self.sign_up_button.setObjectName("sign_up_button")
        self.background_image = QtWidgets.QLabel(self.centralwidget)
        self.background_image.setGeometry(QtCore.QRect(0, 0, 301, 301))
        self.background_image.setText("")
        self.background_image.setObjectName("background_image")
        self.background_image.raise_()
        self.label.raise_()
        self.account_Inputer.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.Password_Inputer.raise_()
        self.Teacher_QRadio.raise_()
        self.Student_QRadio.raise_()
        self.sign_in_button.raise_()
        self.sign_up_button.raise_()
        Sign_in_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Sign_in_window)
        QtCore.QMetaObject.connectSlotsByName(Sign_in_window)

    def retranslateUi(self, Sign_in_window):
        _translate = QtCore.QCoreApplication.translate
        Sign_in_window.setWindowTitle(_translate("Sign_in_window", "登录"))
        self.label.setText(_translate("Sign_in_window", "考试系统"))
        self.label_2.setText(_translate("Sign_in_window", "账号："))
        self.label_3.setText(_translate("Sign_in_window", "密码："))
        self.Teacher_QRadio.setText(_translate("Sign_in_window", "老师"))
        self.Student_QRadio.setText(_translate("Sign_in_window", "学生"))
        self.sign_in_button.setText(_translate("Sign_in_window", "登录"))
        self.sign_up_button.setText(_translate("Sign_in_window", "注册"))
